
0: Blockchain.class
	java -cp ".:gson-2.8.2.jar" Blockchain
1: Blockchain.class
	java -cp ".:gson-2.8.2.jar" Blockchain 1
2: Blockchain.class
	java -cp ".:gson-2.8.2.jar" Blockchain 2

Blockchain.class: Blockchain.java
	javac -cp "gson-2.8.2.jar" Blockchain.java

.PHONY: clean
clean: 
	rm -f *.class
